version: '3'
services:
  docs:
    build: .
    ports:
      - '3015:80'
    networks:
        - default
    volumes:
     - .:/home/node/app
     - /home/node/app/node_modules

networks:
  default:
    external:
      name: dev